### ISSUE TITLE
App responsivness

### ISSUE THREAD

**Issue by Cholewka** [Cholewka/ClassRegister#1]
The RWD aspect of the application is not going very well. It's not the priority to fix the styling for mobile versions, but it's must-have on first production.

## To-do:
- [ ] Add hamburger to navigation menu
- [ ] Fix the sidebar of panel
- [ ] Fix the grid of panel, make it more mobile-friendly
- [ ] N/A
